### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Marusia14/__grid-template#1]
1)
Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам HTML, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://user-images.githubusercontent.com/8464662/134761140-84ecca5e-5ce8-41ba-9569-51c4b33d1e1a.png)

2)
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/134761190-dd0f9b6e-ba75-451e-9952-3aafd7b4d664.png)

3)
хорошо видно?
![image](https://user-images.githubusercontent.com/8464662/134761219-d8f5294b-b26e-4397-8823-ad8f66e7ddb7.png)

**Comment by Marusia14** [comment]
page:
https://marusia14.github.io/__grid-template/

repository:
https://github.com/Marusia14/__grid-template.git

сб, 25 вер. 2021 о 09:28 Andrey ***@***.***> пише:

**Comment by Alecto** [comment]
2 - заполнитель, не исправлено

**Comment by Marusia14** [comment]
Page:
https://marusia14.github.io/__grid-template/

Repository:
https://github.com/Marusia14/__grid-template.git

сб, 25 вер. 2021 о 14:10 Andrey ***@***.***> пише:

**Comment by Alecto** [comment]
Хорошо, ошибок и замечаний нет.
Работа принята.

сб, 25 вер. 2021 о 14:55 Marusia14 ***@***.***> пише:

**Comment by Alecto** [comment]
напишите, кому ставить оценку, в переписке через гитхаб данные не
присуствуют

нд, 26 вер. 2021 о 09:27 Андрей Фоменко ***@***.***> пише:

**Comment by Marusia14** [comment]
[image: image.png]
В профиль на github тоже добавила имя и фамилию)

нд, 26 вер. 2021 о 09:28 Andrey ***@***.***> пише:

**Comment by Alecto** [comment]
отметил )

нд, 26 вер. 2021 о 11:58 Мария Лемиш ***@***.***> пише:
